name: Hello World!

on:
  push:
    branches:
      - master

jobs:
  hello_world:
    runs-on: ubuntu-20.04
    steps:
      - name: Say Hello
        run: |
          echo "Hello World!"
      - name: Print Date
        run: |
          date
      - name: Print Directory Content
        run: |
          ls -l
